<div id="m2-component" data-bind="scope:'locations'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#m2-component": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "locations": {
                        "component": "Fastgento_Storelocator/js/model/locations",
                        "template" : "Fastgento_Storelocator/locations",
                        "dataTest" : "dsdfsdfsdfsdfs"
                    }
                }
            }
        }
    }
    </script>
</div>