<?php
/**
 * Copyright © 2015 Fastgento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<form class="form minisearch">
    <div class="field search">
        <label class="label" for="search" data-role="minisearch-label">
            <span><?php echo __("Search Store"); ?></span>
        </label>
        <div class="control">
            <input id="search" type="text" name="q" value="" placeholder="Search entire store here..." class="input-text" maxlength="128" role="combobox" aria-haspopup="false" aria-autocomplete="both" autocomplete="off">
            <div id="search_autocomplete" class="search-autocomplete" style="display: none;"></div>
        </div>
        <div class="primary"><button type="submit" class="action login primary" name="send" id="map_search"><span><?php echo __("Search Store"); ?></span></button></div>
    </div>
</form>
<?php /** @var $block \Fastgento\Storelocator\Block\Locator\Map */ ?>
<div class="map-wrapper" data-mage-init='{"mapGoogle":<?php echo $block->getSerializedOptions();?>}'>
    <div id="map"></div>
</div>